### ISSUE TITLE
Error retrieving checkpoint origin state and block

### ISSUE THREAD

**Issue by YuXiaoCoder** [ethpandaops/checkpointz#158]
Network: ETH Goerli
Cmd: `/opt/eth-goerlimain/core/beacon-chain --goerli --datadir=/mnt/eth-goerlimain/node/prysm/beacon --genesis-state=/mnt/eth-goerlimain/conf/goerli-genesis.ssz --rpc-host=0.0.0.0 --rpc-port=4000 --rpc-max-page-size=200000 --grpc-gateway-host=0.0.0.0 --grpc-gateway-port=3500 --grpc-gateway-corsdomain=* --grpc-max-msg-size=268435456 --p2p-tcp-port=13000 --p2p-udp-port=12000 --execution-endpoint=http://127.0.0.1:8551 --disable-monitoring --http-modules=prysm,eth --enable-historical-state-representation --save-full-execution-payloads --enable-eip-4881 --checkpoint-sync-url=https://sync-goerli.beaconcha.in --genesis-beacon-api-url=https://sync-goerli.beaconcha.in --blob-save-fsync --accept-terms-of-use --jwt-secret=/mnt/eth-goerlimain/node/jwt.hex --suggested-fee-recipient=0x958FC6D1601AC1416107f113BE401e80b7E6aF5D --http-mev-relay=http://127.0.0.1:18550`
Version: `5.0.1`
Error Log:
```log
time="2024-03-11 14:35:50" level=warning msg="database contains genesis with htr=0x895390e92edc03df7096e9f51e51896e8dbe6e7e838180dadbfd869fdd77a659, ignoring remote genesis state parameter" prefix=genesis
time="2024-03-11 14:35:51" level=info msg="detected supported config in remote finalized state, name=prater, fork=deneb"
unable to start beacon node: Error retrieving checkpoint origin state and block: error requesting block by slot = 7602560: error requesting state by id = 7602560: code=500, url=https://sync-goerli.beaconcha.in/eth/v2/beacon/blocks/7602560, body=response body:
{"code":500,"message":"not found"}: did not receive 2xx response from API
```

**Comment by samcm** [comment]
Thanks for the issue @YuXiaoCoder !

Goerli is EOL, and hasn't finalized for a few days. Unrelated to checkpointz so going to close this one out. 🙏
