### ISSUE TITLE
EIP-4881 deposit snapshot support

### ISSUE THREAD

**Issue by michaelsproul** [ethpandaops/checkpointz#74]
A new endpoint for quickly synchronising the execution layer deposit cache during checkpoint sync is being standardised in https://github.com/ethereum/beacon-APIs/pull/245.

This API will be available in Lighthouse in our next release v3.3.0, and we would like to support it for our checkpointz instance (`mainnet.checkpoint.sigp.io`) and other checkpointz servers running Lighthouse.

Unfortunately my own Go skills are too poor to help with implementation in `checkpointz`, but if someone had time to implement this I would be very grateful :blush:

**Comment by samcm** [comment]
We can certainly have a look at that @michaelsproul! Thanks for the issue 👍

**Comment by pietjepuk2** [comment]
Taking a look at the finalization conditions in the [EIP](https://eips.ethereum.org/EIPS/eip-4881#deposit-finalization-conditions), am I correct in understanding that the checkpoint that should be served is not necessarily the latest `finalized` anymore?

If there are more deposits than can be handled in a `EPOCHS_PER_ETH1_VOTING_PERIOD`, the above-linked "deposit finalization conditions" are not satisfied, and then the checkpoint that should be served should be an older one. Hypothetically (if there are a _lot_ of deposits), a _much_ older one.

**Comment by ethDreamer** [comment]
Hello @pietjepuk2,

> am I correct in understanding that the checkpoint that should be served is not necessarily the latest finalized anymore?

Not quite. The checkpoint that the `DepositTreeSnapshot` corresponds to is completely independent of the `finalized` checkpoint that is served to the node.

In most cases, the `DepositTreeSnapshot` checkpoint **will** be older than the latest `finalized` checkpoint. But that's totally fine. The deposit snapshot is just the starting point for syncing deposits, which without the snapshot is all the way back at the launch of the deposit contract. Nodes are perfectly free to start following the chain from the latest `finalized` checkpoint, but start syncing deposits from an older checkpoint :)

Lighthouse will automatically serve the latest snapshot that satisfies the [deposit finalization conditions](https://eips.ethereum.org/EIPS/eip-4881#deposit-finalization-conditions).

**Comment by pietjepuk2** [comment]
OK, that makes total sense! Got a bit confused with all the checkpoint/finalization nomenclature, thanks for elaborating :)

**Comment by samcm** [comment]
Haven't had a chance to implement this yet but just noting that it's still on my TODO list 🙏. I'll be making some updates to support Shapella in the next few weeks so will likely be bundled in around then 👍

**Comment by pietjepuk2** [comment]
I'm not entirely sure how relevant snapshot deposit support is on the long term with https://eips.ethereum.org/EIPS/eip-6110 . I don't know how many clients will support 4881 (or 6110 for that matter), but thought I'd say least mention it here.

**Comment by ethDreamer** [comment]
Bumping this. Any progress @samcm ?

**Comment by samcm** [comment]
Having a look now. Am I correct in saying that there isn't any additional logic required in serving this endpoint? Checkpointz currently operates like this:
- Wait around until a majority of the configured upstreams agree on a new finalized checkpoint
- Pick one of those nodes and fetch the "bundle" for the checkpoint (`beacon block` and `beacon state`)
- If the `block` is on an epoch boundary start serving the "bundle" via the HTTP API.

Is the change as simple as including the `deposit snapshot` in the "bundle" and serving with the equivalent `beacon block` and `beacon state`?

**Comment by ethDreamer** [comment]
you could implement it this way, though for many (`beacon block`, `beacon state`) tuples, the snapshot will be the same. It changes less often than the finalized checkpoint.

**Comment by ethDreamer** [comment]
Mind if I bump this again?

**Comment by ethDreamer** [comment]
Mind if I bump this again @samcm ?

**Comment by samcm** [comment]
I've got the bulk of this working @ethDreamer, with the last remaining task being ssz support. Might just roll with JSON support for now - can revisit if needed down the track
